"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent  # Go up to the main project root

# Add the root frontend directory to Python path
import sys
sys.path.insert(0, str(PROJECT_ROOT))

# Add the law_information_project to Python path
sys.path.insert(0, str(PROJECT_ROOT / "backend" / "law_information_project"))

# Load environment variables
PINECONE_API_KEY = config('PINECONE_API_KEY', default='')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^z2@d-(!#r*bhx%n70h!-34b3ri3+4^i_0ink0yidx9n1#e(t!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # Django REST Framework
    "apps.accounts",  # User accounts and profiles
    "corsheaders",  # CORS headers
    "apps.cases",  # Cases app for your scraper
    "search_indexing",  # Search indexing app
    "search_benchmarking",  # Search benchmarking app
    "frontend",  # Frontend app
    "law_information",  # Law Information Resource app
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            PROJECT_ROOT / "frontend" / "templates",  # New frontend templates
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "ihc_cases_db",
        "USER": "postgres",
        "PASSWORD": "zakirposgresql",  # Replace with your PostgreSQL password
        "HOST": "localhost",
        "PORT": "5432",
    },
    "law_information": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "law_information_db",
        "USER": "postgres",
        "PASSWORD": "zakirposgresql",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Database routing for law_information app
DATABASE_ROUTERS = ['core.database_router.LawInformationRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
    PROJECT_ROOT / "frontend" / "static",  # New frontend static files
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Model cache directory to reduce Hugging Face API calls
MODEL_CACHE_DIR = BASE_DIR / "model_cache"
MODEL_CACHE_DIR.mkdir(exist_ok=True)

# Sentence Transformer settings
SENTENCE_TRANSFORMERS_HOME = str(MODEL_CACHE_DIR)

# Suppress Hugging Face symlinks warning on Windows
import os
os.environ['HF_HUB_DISABLE_SYMLINKS_WARNING'] = '1'

# Learned reranker settings
LEARNED_RERANKER_DIR = BASE_DIR / "models" / "rerankers"
LEARNED_RERANKER_DIR.mkdir(parents=True, exist_ok=True)
LEARNED_RERANKER_MODEL_NAME = config("LEARNED_RERANKER_MODEL", default="").strip()
LEARNED_RERANKER_MODEL_PATH = (
    (LEARNED_RERANKER_DIR / LEARNED_RERANKER_MODEL_NAME)
    if LEARNED_RERANKER_MODEL_NAME
    else None
)

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
