# Generated by Django 5.2.5 on 2025-09-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("law_information", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary category for this law",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="law_information.lawcategory",
            ),
        ),
    ]
