# Generated by Django 5.2.5 on 2025-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_indexing", "0004_add_enhanced_metadata_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexingconfig',
            name='embedding_model',
            field=models.CharField(default='all-mpnet-base-v2', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexingconfig',
            name='embedding_dimension',
            field=models.IntegerField(default=768),
        ),
    ]
