# Generated by Django 5.2.4 on 2025-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_indexing", "0006_widen_facet_term_canonical"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_id", models.IntegerField()),
                ("document_id", models.IntegerField(blank=True, null=True)),
                (
                    "chunk_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("chunk_index", models.IntegerField()),
                ("chunk_text", models.TextField()),
                ("start_char", models.IntegerField()),
                ("end_char", models.IntegerField()),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("chunk_hash", models.CharField(db_index=True, max_length=64)),
                ("token_count", models.IntegerField()),
                ("is_embedded", models.BooleanField(default=False)),
                ("embedding_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "document_chunks",
            },
        ),
        migrations.CreateModel(
            name="SearchMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_id", models.IntegerField()),
                (
                    "case_number_normalized",
                    models.CharField(db_index=True, max_length=300),
                ),
                (
                    "case_title_normalized",
                    models.CharField(db_index=True, max_length=800),
                ),
                ("parties_normalized", models.TextField(blank=True)),
                ("court_normalized", models.CharField(db_index=True, max_length=100)),
                ("status_normalized", models.CharField(db_index=True, max_length=50)),
                (
                    "institution_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "hearing_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "disposal_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("legal_entities", models.JSONField(blank=True, default=list)),
                ("legal_concepts", models.JSONField(blank=True, default=list)),
                ("case_classification", models.JSONField(blank=True, default=dict)),
                ("subject_matter", models.JSONField(blank=True, default=list)),
                ("parties_intelligence", models.JSONField(blank=True, default=dict)),
                (
                    "procedural_stage",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("case_timeline", models.JSONField(blank=True, default=list)),
                (
                    "content_richness_score",
                    models.FloatField(db_index=True, default=0.0),
                ),
                (
                    "data_completeness_score",
                    models.FloatField(db_index=True, default=0.0),
                ),
                ("authority_score", models.FloatField(db_index=True, default=0.0)),
                ("precedential_value", models.FloatField(db_index=True, default=0.0)),
                ("searchable_keywords", models.JSONField(blank=True, default=list)),
                ("semantic_tags", models.JSONField(blank=True, default=list)),
                ("relevance_boosters", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("text_hash", models.CharField(db_index=True, max_length=64)),
                ("metadata_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "enhanced_metadata_hash",
                    models.CharField(db_index=True, default="", max_length=64),
                ),
                ("total_chunks", models.IntegerField(default=0)),
                ("total_terms", models.IntegerField(default=0)),
                ("avg_chunk_length", models.FloatField(default=0.0)),
                ("is_indexed", models.BooleanField(default=False)),
                (
                    "enhanced_metadata_extracted",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("last_indexed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_metadata",
            },
        ),
        migrations.RenameIndex(
            model_name="facetmapping",
            new_name="facet_mappi_case_id_b92c5c_idx",
            old_name="facet_mappin_case_i_0e1e1e_idx",
        ),
        migrations.RenameIndex(
            model_name="facetmapping",
            new_name="facet_mappi_facet_t_65834b_idx",
            old_name="facet_mappin_facet__1f2f2f_idx",
        ),
        migrations.RenameIndex(
            model_name="facetterm",
            new_name="facet_terms_facet_t_512f6b_idx",
            old_name="facet_terms_facet_t_occurre_7b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="facetterm",
            new_name="facet_terms_facet_t_60de46_idx",
            old_name="facet_terms_facet_t_case_c_8c9c9c_idx",
        ),
        migrations.RenameIndex(
            model_name="facetterm",
            new_name="facet_terms_canonic_98b8b1_idx",
            old_name="facet_terms_canonic_9d0d0d_idx",
        ),
        migrations.AddIndex(
            model_name="indexinglog",
            index=models.Index(
                fields=["operation_type"], name="indexing_lo_operati_32bff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexinglog",
            index=models.Index(
                fields=["index_type"], name="indexing_lo_index_t_7ca4d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexinglog",
            index=models.Index(
                fields=["is_successful"], name="indexing_lo_is_succ_ca3a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexinglog",
            index=models.Index(
                fields=["started_at"], name="indexing_lo_started_72fd6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["chunk_hash"], name="document_ch_chunk_h_831f27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["is_embedded"], name="document_ch_is_embe_2fc846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["page_number"], name="document_ch_page_nu_91bcc3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("case_id", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="searchmetadata",
            index=models.Index(
                fields=["case_number_normalized"], name="search_meta_case_nu_6bb2e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmetadata",
            index=models.Index(
                fields=["court_normalized"], name="search_meta_court_n_ae2049_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmetadata",
            index=models.Index(
                fields=["status_normalized"], name="search_meta_status__a270c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmetadata",
            index=models.Index(
                fields=["institution_date"], name="search_meta_institu_e25489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmetadata",
            index=models.Index(
                fields=["disposal_date"], name="search_meta_disposa_e71ee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmetadata",
            index=models.Index(
                fields=["is_indexed"], name="search_meta_is_inde_338259_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchmetadata",
            unique_together={("case_id",)},
        ),
    ]
