# Generated manually for initial cases app setup

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=255)),
                ('institution_date', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number', models.CharField(max_length=255)),
                ('case_title', models.TextField(blank=True, null=True)),
                ('bench', models.CharField(blank=True, max_length=255, null=True)),
                ('hearing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('history_options', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.court')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_status', models.CharField(blank=True, max_length=255, null=True)),
                ('hearing_date_detailed', models.CharField(blank=True, max_length=255, null=True)),
                ('case_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('tentative_date', models.CharField(blank=True, max_length=255, null=True)),
                ('short_order', models.TextField(blank=True, null=True)),
                ('before_bench', models.CharField(blank=True, max_length=255, null=True)),
                ('case_title_detailed', models.TextField(blank=True, null=True)),
                ('advocates_petitioner', models.TextField(blank=True, null=True)),
                ('advocates_respondent', models.TextField(blank=True, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('disposed_of_status', models.CharField(blank=True, max_length=255, null=True)),
                ('case_disposal_date', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_bench', models.CharField(blank=True, max_length=255, null=True)),
                ('consigned_date', models.CharField(blank=True, max_length=255, null=True)),
                ('fir_number', models.CharField(blank=True, max_length=255, null=True)),
                ('fir_date', models.CharField(blank=True, max_length=255, null=True)),
                ('police_station', models.CharField(blank=True, max_length=255, null=True)),
                ('under_section', models.CharField(blank=True, max_length=255, null=True)),
                ('incident', models.TextField(blank=True, null=True)),
                ('name_of_accused', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='JudgementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('pdf_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=255)),
                ('hearing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('bench', models.CharField(blank=True, max_length=255, null=True)),
                ('list_type', models.CharField(blank=True, max_length=255, null=True)),
                ('case_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('short_order', models.TextField(blank=True, null=True)),
                ('disposal_date', models.CharField(blank=True, max_length=255, null=True)),
                ('view_link', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_date', models.CharField(max_length=255)),
                ('case_no', models.CharField(max_length=255)),
                ('case_title', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('parties', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('view_link', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseCmsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=255)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_date', models.CharField(blank=True, max_length=255, null=True)),
                ('order_passed', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='PartiesDetailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_number', models.CharField(max_length=255)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party_side', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsDetailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_date', models.CharField(max_length=255)),
                ('case_no', models.CharField(max_length=255)),
                ('case_title', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('parties', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('view_link', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseCmsDetailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=255)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_date', models.CharField(blank=True, max_length=255, null=True)),
                ('order_passed', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='HearingDetailsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=255)),
                ('hearing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('bench', models.CharField(blank=True, max_length=255, null=True)),
                ('list_type', models.CharField(blank=True, max_length=255, null=True)),
                ('case_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('short_order', models.TextField(blank=True, null=True)),
                ('disposal_date', models.CharField(blank=True, max_length=255, null=True)),
                ('view_link', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_data', models.JSONField(blank=True, null=True)),
                ('comments_data', models.JSONField(blank=True, null=True)),
                ('case_cms_data', models.JSONField(blank=True, null=True)),
                ('judgement_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetailOptionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties_detail_data', models.JSONField(blank=True, null=True)),
                ('comments_detail_data', models.JSONField(blank=True, null=True)),
                ('case_cms_detail_data', models.JSONField(blank=True, null=True)),
                ('hearing_details_detail_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='ViewLinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
