# Generated by Django 5.2.5 on 2025-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="qasession",
            name="qa_sessions_user_id_d0c56b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="qafeedback",
            unique_together={("response", "user_id")},
        ),
        migrations.RemoveField(
            model_name="qasession",
            name="user",
        ),
        migrations.AddField(
            model_name="qafeedback",
            name="user_id",
            field=models.CharField(db_index=True, default="anonymous", max_length=100),
        ),
        migrations.AddField(
            model_name="qasession",
            name="user_id",
            field=models.CharField(db_index=True, default="anonymous", max_length=100),
        ),
        migrations.AddIndex(
            model_name="qasession",
            index=models.Index(
                fields=["user_id", "is_active"], name="qa_sessions_user_id_d0c56b_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="qafeedback",
            name="user",
        ),
    ]
